service: preview-poc

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_DEFAULT_REGION, 'ap-south-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
